db:
  build: db/
  ports:
    - "5432"
redis:
  image: 'redis:3.0.0'
  command: redis-server --appendonly yes  # Start with persistent storage.
  ports:
    - "6379"
web:
  build: .
  env_file:
    - .env
  volumes:
    - .:/home/app/myapp
  ports:
    - "80:80"
  links:
    - db
    - redis
